language: node_js
node_js:
  - lts/*

cache: yarn

before_script:
   - npm install -g firebase-tools

script:
  - npm run build

after_success:
  - firebase use --token $FIREBASE_DEPLOY_KEY daycore-9aee3
  - firebase deploy --non-interactive --token $FIREBASE_DEPLOY_KEY

branches:
  only:
  - master
